# schema.act is generated by rfcgen.act by reading the YANG RFC 7950, which is
# stored in the rfc module.

all: src/yang/schema.act
	acton build

.PHONY: gen
gen: src/yang/schema.act

src/yang/schema.act: gen/schema-header.act gen/schema-footer.act gen/out/bin/rfcgen
	cd gen && out/bin/rfcgen > ../src/yang/schema.act

gen/out/bin/rfcgen: gen/src/rfcgen.act
	cd gen && acton build

.PHONY: clean
clean:
	rm -rf out

