name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Cache acton stuff"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/acton
          # Hacky cache update:
          # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          key: acton-${{ github.run_id }}
          restore-keys: |
            acton
      - run: |
          make gen
          git diff --exit-code
      - run: acton build
      - run: acton test
      - run: acton test perf
      - run: make test-daclass
      - run: make test-data-source-roundtrip
      # another diff check because test-daclass also generates code
      - run: git diff --exit-code
      - run: make test-yang-compile

  test-orchestron:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out orchestron repository code"
        uses: actions/checkout@v4
        with:
          repository: orchestron-orchestrator/orchestron
      - name: "Update yang library dependency"
      # We use the commit SHA for both the main orchestron app and gen_dmc, to ensure we're getting the same Zig package hash in both
        run: |
          acton pkg add https://github.com/orchestron-orchestrator/acton-yang/archive/${{ github.sha }}.zip yang
          cd gen_dmc
          acton pkg add https://github.com/orchestron-orchestrator/acton-yang/archive/${{ github.sha }}.zip yang
      - name: "Regenerate orchestron adata"
        run: |
          make
          git diff
      - name: "Run orchestron tests"
        run: |
          acton test
          acton test perf
