name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Acton from APT tip repo"
        run: |
          wget -q -O - https://apt.acton-lang.io/acton.gpg | sudo apt-key add -
          #echo "deb [arch=amd64] http://apt.acton-lang.io/ stable main" | sudo tee /etc/apt/sources.list.d/acton.list
          echo "deb [arch=amd64] http://aptip.acton-lang.io/ tip main" | sudo tee /etc/apt/sources.list.d/acton.list
          sudo apt-get update
          sudo apt-get install -qy acton
          acton --version
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - run: acton build
      - run: acton test
      - run: acton test perf
