name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - run: |
          make gen
          git diff --exit-code
      - run: acton build
      - run: acton test
      - run: acton test perf
      - run: make test-daclass
      # another diff check because test-daclass also generates code
      - run: git diff --exit-code
